import { Router } from 'express';
import { container } from 'tsyringe';
import { BookingController } from '../controllers/BookingController.js';
import { paymentCallbackRateLimiter } from '@presentation/shared/middlewares/rateLimiters';
const router = Router();
const controller = container.resolve(BookingController);
router.post('/payu/success', paymentCallbackRateLimiter, controller.payuSuccess);
router.post('/payu/failure', paymentCallbackRateLimiter, controller.payuFailure);
router.post('/payu/webhook', paymentCallbackRateLimiter, controller.webhook);
export default router;
