export enum TurfOnboardingErrorCode {
  INVALID_LOCATION = 'TURF_ONBOARDING_INVALID_LOCATION',
  INVALID_COORDINATES = 'TURF_ONBOARDING_INVALID_COORDINATES',
  INVALID_DOCUMENT = 'TURF_ONBOARDING_INVALID_DOCUMENT',
  INVALID_IMAGE = 'TURF_ONBOARDING_INVALID_IMAGE',
  DUPLICATE_PENDING_APPLICATION = 'TURF_ONBOARDING_DUPLICATE_PENDING',
  APPLICATION_NOT_FOUND = 'TURF_ONBOARDING_NOT_FOUND',
  ALREADY_REVIEWED = 'TURF_ONBOARDING_ALREADY_REVIEWED',
}
